# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/miuicamera/common

PRODUCT_COPY_FILES += \
    vendor/miuicamera/common/proprietary/etc/default-permissions/miuicamera-permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/default-permissions/miuicamera-permissions.xml \
    vendor/miuicamera/common/proprietary/etc/permissions/privapp-permissions-miuicamera.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-miuicamera.xml \
    vendor/miuicamera/common/proprietary/vendor/camera/fonts/MFYueYuan-Regular.ttf:$(TARGET_COPY_OUT_VENDOR)/camera/fonts/MFYueYuan-Regular.ttf \
    vendor/miuicamera/common/proprietary/vendor/camera/fonts/MI+LanTing_GB+Outside+YS_V2.3_20160322.ttf:$(TARGET_COPY_OUT_VENDOR)/camera/fonts/MI+LanTing_GB+Outside+YS_V2.3_20160322.ttf \
    vendor/miuicamera/common/proprietary/vendor/camera/fonts/MIUI_Time.ttf:$(TARGET_COPY_OUT_VENDOR)/camera/fonts/MIUI_Time.ttf \
    vendor/miuicamera/common/proprietary/vendor/etc/camera/beauty_ui9_intelligent_params.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beauty_ui9_intelligent_params.config

PRODUCT_PACKAGES += \
    libcom.xiaomi.camera.requestutil \
    libjni_jpegutil_xiaomi \
    libmorpho_memory_allocator \
    libmorpho_sensor_fusion \
    libCameraEffectJNI \
    libarc_layer_sgl \
    libarcsoft_wideselfie \
    libcamera_arcsoft_beautyshot \
    libcamera_arcsoft_handgesture \
    libcamera_beauty_mpbase \
    libcamera_handgesture_mpbase \
    libcamera_wideselfie_mpbase \
    libhandengine.arcsoft \
    libjni_arcsoft_beautyshot \
    libjni_wideselfie \
    libmorpho_panorama_gp3 \
    MiuiCamera
